name: unittest
version: 0.12.2
author: Dart Team <misc@dartlang.org>
description: A library for writing dart unit tests.
homepage: https://github.com/dart-lang/test
dependencies:
  test: ">=0.12.0 <0.12.1"
